### ISSUE TITLE
Equity Analysis feature? 

### ISSUE THREAD

**Issue by def-mycroft** [charleskawczynski/HoldemHandEvaluator.jl#38]
Hi, I'd like to use Julia to analyze range vs range equity - is this project one that might include this feature? This might be beyond the scope of this project, but thought I'd at least raise the question.

**Comment by charleskawczynski** [comment]
Hi @def-mycroft,

I think range & equity are outside the scope of PokerHandEvaluator.jl, since range & equity involve bets and potential hands of other players, while PokerHandEvaluator.jl's goal is to compare two 5-7 card hands--it doesn't need to know of, or understand, players or bets. I think analyzing range vs equity is definitely in the scope of [TexasHoldem.jl](https://github.com/charleskawczynski/TexasHoldem.jl), though!

Also, just to point out, I have a very rough draft of [PokerBots.jl](https://github.com/charleskawczynski/PokerBots.jl) 🙂. I wanted to put all of these packages into an organization but, if I remember correctly, I wasn't able to use some github apps, so I decided to keep them all under my own account.

**Comment by def-mycroft** [comment]
Hi Charles! Thanks for your response, totally makes sense that take range
equity would be out of scope.

I was just thinking about all-in range vs range equity on different
streets, so that wouldn't involve bets etc, but that would be out of scope
too i.e. two 5-7 card hands.

Very nice code here! Julia is so great, I really should move away from
python in a lot of cases, I end up writing code in python that is too slow
and then rewrite in Julia.

Thanks for the recommendation on TexasHoldem.jl, was hoping you'd have
something to suggest.

**Comment by def-mycroft** [comment]
I'll check out PokerBots too :)
